export const SET_ARR_ROOM = "SET_ARR_ROOM";
export const SET_ROOM_DATA_BY_ID = "SET_ROOM_DATA_BY_ID";
export const SET_ARR_ROOM_BY_PANIGATION = "SET_ARR_ROOM_BY_PANIGATION";
export const SET_LOADING_ROOM = "SET_LOADING_ROOM";
