export const SET_ARR_LOCATIONS = "SET_ARR_LOCATIONS";
export const SET_ARR_LOCATIONS_BY_PAGINATION = "SET_ARR_LOCATIONS_BY_PAGINATION";
export const SET_LOCATION_DATA_BY_ID = "SET_LOCATION_DATA_BY_ID";
export const SET_LOADING_LOCATION = "SET_LOADING_LOCATION";